# Generated by Django 5.2.6 on 2025-09-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_managementAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitem')},
        ),
    ]
