# Generated by Django 5.2.6 on 2025-09-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managementAPI', '0002_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
